### ISSUE TITLE
Cloudwatch logger raises error on AccessDenied

### ISSUE THREAD

**Issue by slemrmartin** [RedHatInsights/topological_inventory-providers-common#9]
TPINVTRY-819

There are bad/missing/deprecated(?) credentials to aws logger. It causes unexpected exceptions.

manageiq-loggers version >= 4.2 solves it

- [x] https://github.com/RedHatInsights/sources-api/pull/154
- [x] https://github.com/RedHatInsights/topological_inventory-api/pull/271
- [x] https://github.com/RedHatInsights/topological_inventory-amazon/pull/46
- [x] https://github.com/RedHatInsights/topological_inventory-ansible_tower/pull/54
- [x] https://github.com/RedHatInsights/topological_inventory-azure/pull/9
- [x] https://github.com/RedHatInsights/topological_inventory-ingress_api/pull/75
- [x] https://github.com/RedHatInsights/topological_inventory-openshift/pull/109
- [x] https://github.com/RedHatInsights/topological_inventory-providers-common/pull/10
- [x] https://github.com/RedHatInsights/topological_inventory-orchestrator/pull/65
- [x] https://github.com/RedHatInsights/topological_inventory-sync/pull/55
- [x] https://github.com/RedHatInsights/topological_inventory-persister/pull/47

**Comment by bdunne** [comment]
:+1: Thanks for the updates
